name: Monthly Rent Reminders

on:
  schedule:
    # Run at 9:00 AM UTC on the 5th of every month
    - cron: '0 9 5 * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd room_service
        pip install -r ../requirements.txt
        
    - name: Run monthly reminders
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
      run: |
        cd room_service
        python monthly_reminder_scheduler.py
